/**
 * Redirect generation.
 *
 * When a route moves to a sibling property, serving a 404 throws away every
 * ranking signal the old URL earned. A 301 transfers them to the new owner,
 * so the rules are generated from `movedRoutes` in config.js and can never
 * drift away from what the audit enforces.
 */

const fs = require('fs');
const path = require('path');

const { site, movedRoutes } = require('./config');

/**
 * @returns {string} An nginx server block implementing every moved route.
 */
function generateNginx() {
  const host = new URL(site.url).host;
  const lines = [
    '# Generated by seo/redirects.js - do not edit by hand.',
    '# Regenerate with: node seo/build.js redirects',
    '#',
    '# Permanent redirects for routes that moved to a sibling property.',
    '# 301 (not 302) so the accumulated ranking signals transfer.',
    '',
    `# server_name ${host};`,
    '',
  ];

  const entries = Object.entries(movedRoutes);
  if (entries.length === 0) {
    lines.push('# No moved routes are configured.');
  }

  for (const [from, to] of entries) {
    lines.push(`location = ${from} {`);
    lines.push(`    return 301 ${to};`);
    lines.push('}');
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

/**
 * Apache equivalent, for hosts that read .htaccess instead of nginx config.
 *
 * @returns {string}
 */
function generateApache() {
  const lines = [
    '# Generated by seo/redirects.js - do not edit by hand.',
    '# Regenerate with: node seo/build.js redirects',
    '',
  ];

  for (const [from, to] of Object.entries(movedRoutes)) {
    lines.push(`Redirect 301 ${from} ${to}`);
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

/**
 * @param {string} rootDir
 * @returns {{ nginxPath: string, count: number }}
 */
function writeRedirects(rootDir) {
  const dir = path.join(rootDir, 'nginx');
  fs.mkdirSync(dir, { recursive: true });

  const nginxPath = path.join(dir, 'moved-routes.conf');
  fs.writeFileSync(nginxPath, generateNginx());

  return { nginxPath, count: Object.keys(movedRoutes).length };
}

module.exports = { generateNginx, generateApache, writeRedirects };
